title: Grace Matherne
logo: https://github.com/gracevmath/gracevmath.github.io/blob/main/Logo.jpeg
description: I am a recent graduate in love with computation and data visualization.
#show_downloads: true
theme: jekyll-theme-minimal
